### ISSUE TITLE
Window not shown unless get_surface is called.

### ISSUE THREAD

**Issue by backwardspy** [marcusva/py-sdl2#139] opened 2019-05-29 11:27 UTC
I've put together a minimal example of opening a window with PySDL2. I'm not sure what I'm missing, but my window only shows up if I include a call to `window.get_surface()` (even if I throw away the result.)

Here's my (working) example:

```python
import sys
import sdl2
import sdl2.ext


def main():
    sdl2.ext.init()
    window = sdl2.ext.Window("PySDL2 Test", size=(320, 200))
    window.show()

    window.get_surface()

    sdl2.ext.TestEventProcessor().run(window)

    sdl2.ext.quit()
    return 0


if __name__ == "__main__":
    sys.exit(main())
```

If I comment out line 11 (`window.get_surface()`) then the window is never shown. None of the examples seem to do this, so I feel like I'm missing something.

If it makes any difference, I'm using SwayWM on Wayland.

Thanks!

**Comment by a-hurst** [comment] 2020-01-15 06:20
Hey @backwardspy, thanks for the bug report! Oddly enough, your test script creates a window for me regardless of whether `window.get_surface()` is commented out or not, so it's almost certainly an SDL2 bug and likely a Wayland-specific one. Digging into the docs, the remarks for SDL_GetWindowSurface() (which get_surface() wraps) says:

> A new surface will be created with the optimal format for the window, if necessary. 

so it might be the case that SDL2 on your system doesn't create a surface by default and get_surface() does the job, resulting in the behaviour you're seeing.

If you modify your local copy of pysdl2 to add a call to SDL_GetWindowSurface() in the `show()` function in the `sdl2.ext.window` object like so:

```python
    def show(self):
        """Show the window on the display."""
        video.SDL_ShowWindow(self.window)
       video.SDL_GetWindowSurface(self.window)
```
does that fix the issue on your end? If so, I might officially add it in to the function since it wouldn't really hurt anything and might fix this issue for others.

**Comment by backwardspy** [comment] 2020-01-15 19:30
Hey! Unfortunately I am unable to test your solution, as I no longer have access to the box I was using originally and my current machine is a completely different setup (macOS.) I suspect that something between SDL and Wayland was causing it as you say. Perhaps somebody else who is running Wayland can confirm.

**Comment by a-hurst** [comment] 2020-01-15 20:07
Totally fine @backwardspy, I guess that's what happens when we don't get around to dealing with bug reports for a while! If I have time over the next few weeks I'll see if I can reproduce the issue with a Linux VM in case I can fix this in time for 0.9.7. Thanks again for the report!

**Comment by fthalabi** [comment] 2020-02-15 22:43
@a-hurst  it does fixes the issue for me on my wayland session.

**Comment by fthalabi** [comment] 2020-02-15 22:59
Hi, I'm using the same example as OP
```
import sys
import sdl2
import sdl2.ext


def main():
    sdl2.ext.init()
    window = sdl2.ext.Window("PySDL2 Test", size=(320, 200))
    window.show()

    window.get_surface()

    sdl2.ext.TestEventProcessor().run(window)

    sdl2.ext.quit()
    return 0


if __name__ == "__main__":
    sys.exit(main())
```
the code works with the x11 driver
`SDL_VIDEODRIVER=x11 python test.py `
but it doesn't with the wayland one.
`SDL_VIDEODRIVER=wayland python test.py`
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    sys.exit(main())
  File "test.py", line 8, in main
    window = sdl2.ext.Window("PySDL2 Test", size=(320, 200))
  File "/home/fenho/.local/lib64/python3.6/site-packages/sdl2/ext/window.py", line 49, in __init__
    raise SDLError()
sdl2.ext.common.SDLError: b'failed to create a window surface'
```
@a-hurst i tested the change to sdl2/ext/window.py with no effect.

**Comment by soratobukuroneko** [comment] 2021-04-25 09:40
Same config here (SwayWM) same result using either wayland or x11 drivers

Adding `video.SDL_GetWindowSurface(self.window)` to the `show` method solved the issue.

**Comment by a-hurst** [comment] 2021-05-21 04:01
Finally tested my proposed fix on a old laptop that I tossed Manjaro Sway on. With the extra line, it seems to work! Fixed in the latest commit.

**Closed by a-hurst** 2021-05-21 04:01 UTC
